/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jhcrc5rod5b57knuojw6cd3b6e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-azr3yc3xmjfwxhbu7hh53h3oti",
    "aws_cognito_identity_pool_id": "us-east-1:51e54802-4aa3-4c3a-845e-7057c94fb304",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NzUgn6xU7",
    "aws_user_pools_web_client_id": "3429srdvojd7qqjm1q884390jf",
    "oauth": {}
};


export default awsmobile;
